# Generated by Django 5.0.3 on 2025-12-09 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='survey',
            table='survey_data',
        ),
    ]
